version: '3'

services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=quickyapp
      - MYSQL_USER=root
#      - MYSQL_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3307:3306

  app:
    image: bendevet/please:latest
    ports:
       - 2000:2000
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/quickyapp?autoReconnect=true&useSSL=false
    depends_on:
       - db